spring:
    profiles:
      active:
      - dev
---
spring:
    profiles: dev
    application:
     name: microservicecloud-config-lisen-dev
---
spring:
    profiles: test
    application:
     name: microservicecloud-config-lisen-test  